# Author：周朔鹏
# 编制时间：2025-08-05
# 电子邮件：391902958@qq.com
# 项目官网：https://www.euipd.com

server:
  port: 8009
  servlet:
    context-path: /payproject
spring:
  application:
    name: payproject
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: YOUR_DATABASE_PASSWORD
    url: jdbc:mysql://localhost:3306/mycourse?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
  cloud:
    nacos:
      discovery:
        namespace: public
        username: nacos
        password: nacos
        server-addr: 127.0.0.1:8848
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
  file:
    path: /Users/zhoushuopeng/logs/payproject/
wx:
  appId: wxa275e9779ec92421
  mchId: 1612611921
  mchKey: YOUR_WECHAT_MCH_KEY
  notifyUrl: http://aimall.amiirobot.com/payproject/pay/notify
  returnUrl: http://47.103.58.102:8001/#/order/list
alipay:
  appId: 2018062960540016
  privateKey: "YOUR_WECHAT_PRIVATE_KEY
  publicKey: "YOUR_WECHAT_PUBLIC_KEY
  notifyUrl: http://aimall.amiirobot.com/payproject/pay/notify
  returnUrl: http://47.103.58.102:8001/#/order/list



